# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    javac HelloWorld.java
    jar cfm HelloWorld.jar Manifest.txt HelloWorld.class
    java -jar HelloWorld.jar
    docker build -t helloworld .
    docker images
    docker login registrytestnew.azurecr.io -u 'Registrytestnew' -p 'vi5=32neB63L7wXeFVLZpREaR6lwHk4A'
    docker tag helloworld registrytestnew.azurecr.io/helloworld:latest101
    docker push registrytestnew.azurecr.io/helloworld:latest101
  displayName: 'Run a multi-line script'

